/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmproofgeneration_free: (a: number, b: number) => void;
export const wasmproofgeneration_success: (a: number) => number;
export const wasmproofgeneration_proof_data: (a: number) => [number, number];
export const wasmproofgeneration_public_input_start: (a: number) => bigint;
export const wasmproofgeneration_public_input_result: (a: number) => bigint;
export const wasmproofgeneration_error_message: (a: number) => [number, number];
export const wasmproofgeneration_proof_size_bytes: (a: number) => number;
export const wasmproofgeneration_to_json: (a: number) => [number, number];
export const __wbg_wasmproofverification_free: (a: number, b: number) => void;
export const wasmproofverification_is_valid: (a: number) => number;
export const wasmproofverification_error_message: (a: number) => [number, number];
export const wasmproofverification_to_json: (a: number) => [number, number];
export const __wbg_wasmbenchmarkresult_free: (a: number, b: number) => void;
export const wasmbenchmarkresult_total_proofs: (a: number) => number;
export const wasmbenchmarkresult_successful_proofs: (a: number) => number;
export const wasmbenchmarkresult_total_time_ms: (a: number) => number;
export const wasmbenchmarkresult_average_proof_time_ms: (a: number) => number;
export const wasmbenchmarkresult_average_verification_time_ms: (a: number) => number;
export const wasmbenchmarkresult_proofs_per_second: (a: number) => number;
export const wasmbenchmarkresult_success_rate: (a: number) => number;
export const __wbg_wasmzkprover_free: (a: number, b: number) => void;
export const wasmzkprover_new: () => [number, number, number];
export const wasmzkprover_generate_proof_only: (a: number, b: bigint, c: bigint) => [number, number, number];
export const wasmzkprover_verify_proof_only: (a: number, b: number, c: number, d: bigint, e: bigint) => [number, number, number];
export const wasmzkprover_get_setup_time_ms: (a: number) => number;
export const wasmzkprover_benchmark_generation_only: (a: number, b: number) => [number, number, number];
export const generate_zkp_proof_only: (a: bigint, b: bigint) => [number, number, number];
export const verify_zkp_proof_only: (a: number, b: number, c: bigint, d: bigint) => [number, number, number];
export const verify_computation: (a: bigint, b: bigint, c: bigint) => number;
export const run_generation_benchmark: (a: number) => [number, number, number];
export const get_library_info: () => any;
export const main: () => void;
export const wasmproofverification_verification_time_ms: (a: number) => number;
export const wasmproofgeneration_generation_time_ms: (a: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
